### ISSUE TITLE
Restore von Objekten

### ISSUE THREAD

**Issue by MSteuter** [bheisig/i-doit-api-client-php#1]
Hallo,
ich würde gerne in CMDBObject.php die Restore-Funktion benutzen. Ein Status-Update scheint ja nicht zu klappen.
Gibt es über die API evtl. eine andere Möglichkeit, wie man Objekte wiederherstellen kann? Ist etwas in der Art in Planung? Oder muss ich weiterhin auf die Restore-Funktion verzichten? Damit ist eine Sync-Schnittstelle leider nur schwer abzubilden...

Viele Grüße
Michael

**Comment by bheisig** [comment]
Hallo Michael,

sorry, aber dies scheint der falsche Kanal für deine Fragen zu sein. Bitte kontaktiere den Hersteller von i-doit (synetics). Dieses Projekt verwendet lediglich die API, aber die Entwicklung und der Support derselben liegt bei synetics. Mir ist jedenfalls keine Funktion bekannt, Objekte wiederherzustellen. Daher ist die `restore()`-Methode ausgeklammert.

Viele Grüße
Benjamin
