### ISSUE TITLE
nach update funktioniert api-login nichtmehr

### ISSUE THREAD

**Issue by frisbee23** [bheisig/i-doit-api-client-php#10]
### Expected behavior

normal login into idoit via the api

### Actual behavior

PHP Fatal error:  Uncaught RuntimeException: i-doit responded with an error: i-doit system error: Unable to get userId by credentials in /var/www/itservices/ois/vendor/bheisig/idoitapi/src/API.php:630
Stack trace:
#0 /var/www/itservices/ois/vendor/bheisig/idoitapi/src/API.php(418): bheisig\idoitapi\API->evaluateResponse(Array)
#1 /var/www/itservices/ois/vendor/bheisig/idoitapi/src/API.php(338): bheisig\idoitapi\API->request('idoit.login')
#2 /var/www/itservices/ois/idoit-config.php(15): bheisig\idoitapi\API->login()
#3 /var/www/itservices/ois/fips.php(46): require_once('/var/www/itserv...')
#4 {main}
  thrown in /var/www/itservices/ois/vendor/bheisig/idoitapi/src/API.php on line 630

### Steps to reproduce the behavior

require_once 'vendor/autoload.php';
use bheisig\idoitapi\API;
echo "initializing API...\n";
$api = new API([
    'url' => 'https://i-doit.example.net/src/jsonrpc.php',
    'key' => 'XXXXXXXXX',
    'username' => 'ansible',
    'password' => 'YYYYYYYYYYYYYYYYY'
]);
echo "logging into idoit...\n";
$api->login();

### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| bheisig/idoitapi version  |0.7             |
| PHP version               | 7.0.31             |
| i-doit version            | 1.12 pro   |
| i-doit API add-on version | 1.10           |

### Server logs

Excerpt taken from `/var/log/apache2/error.log`:

~~~
Paste logs
~~~

Excerpt taken from `/var/www/html/i-doit/log/api_*.log`:

~~~
Paste logs
~~~

**Comment by frisbee23** [comment]
- der entsprechende user funktioneirt bei einem normalem login ueber die website

**Comment by frisbee23** [comment]
api_XXXX.log sagt:
[2019-01-15 01:00:58 758070] ERROR: An exception occured while processing request: -32099 i-doit system error: Unable to get userId by credentials

**Comment by bheisig** [comment]
It seems there is an issue in i-doit's API which affects this library. We are currently investigating the problem and provide a fix as soon as possible.

**Comment by frisbee23** [comment]
i use a non-ldap user now, and it works for me again.

**Comment by bheisig** [comment]
Now it's clear: There's a bug in i-doit, not in this library. Dev team identified a problem with LDAP authentification and will fix it asap. Please provide any further information to the i-doit support team. This issue will be closed. Thank you.
