### ISSUE TITLE
Unit-Test "bheisig\idoitapi\tests\Issues\API145Test" fails

### ISSUE THREAD

**Issue by skekec1** [bheisig/i-doit-api-client-php#15]
### Expected behavior

Unit-Test does not fail.

### Actual behavior

Unit-Test works as expected.

### Steps to reproduce the behavior

Run unit test.

### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| bheisig/idoitapi version  | master             |
| i-doit version            | 1.15 pro    |
| i-doit API add-on version | bugfix             |

### Logs and other useful output

Problems in "testAssignSingleObject":

* Passing in objectId as integer for multi selection properties
* Using of undefined category constant "C__CATG__STACKING"

Problems in "testAssignMultipleObjects"

* Expecting exception which is never thrown

**Comment by bheisig** [comment]
Thanks for your report! This is fixed in 8d948926566467a2d15425a67d9b07d21b664b4b.
