### ISSUE TITLE
Fehler "i-doit-api-client-php"-Initialisierung

### ISSUE THREAD

**Issue by Hitsch1976** [bheisig/i-doit-api-client-php#16]
Guten Tag

Ich habe eine neue Installation von i-doit in der Version 1.15.1 PRO und die API in der Version 1.11.2. Für diverse Tests möchte ich den API-Client nutzen. Die Nutzung des Clients erfolgt über "xampp". Bei dem Befehl "Initialize.php" erfolgt die Abfrage für den APi entry-point und den APi-Key. Danach erhalte ich folgende Fehlermeldung;

![image](https://user-images.githubusercontent.com/76481949/102893035-28165200-4461-11eb-9ace-c5143efc5bf0.png)

Ich habe auch eine Testinstallation unter i-doit Version 1.15.2 und der API Version 1.11.3, erhalte aber die gleiche Fehlermeldung.

Herzlichen Dank für Eure Hilfestellung.

Christian

**Comment by bheisig** [comment]
Hello Christian,

it seems like you're referring to another project which is unmaintained for several years now and has nothing to do with this project. I suggest you switch to my API client which is still maintained :-)
